- name: First run 
  hosts: localhost
  vars_files:
   - vars/default.yaml 
  tasks:
  - ansible.builtin.file:
      path: "{{item}}"
      state: touch 
    loop:
      - "/root/first_was_here_2"
    ignore_errors: true

  - ansible.builtin.template:
       src: "templates/{{ item }}.j2"
       dest: "{{ cc.cloud_init_shell }}"
    loop:
     - "cloud-init.sh"

  - user:
     name: ubuntu
     state: absent
     remove: yes
  - debug:
     msg: "{{ansible_facts.ansible_product_serial}}"
  - cron:
     job: test -f {{ cc.cloud_init_shell }} && flock -x  /tmp/robot /bin/bash  {{ cc.cloud_init_shell }}
     hour: 10
     minute: "{{ range(0,60) | random(seed=ansible_facts.ansible_product_serial) }}"
