- name: First run 
  hosts: localhost
  vars_files:
   - vars/default.yaml
  tasks:
  - set_fact:
     myserialhash: "{{ansible_product_serial | hash('sha256')}}"
  
  - debug:
      msg: # 
       - "My serial {{ansible_product_serial}}"
       - "My Serail Hash {{myserialhash}}"
       - "Default hostname would be {{ range(0,1000) | random(seed=ansible_product_serial) }}"

  - ansible.builtin.set_fact:
     cc_secrets: "{{ lookup('ansible.builtin.file', '/root/secrets.yaml') | from_yaml  }}"
    when:
     - ansible_user_id == "root"

  - ansible.builtin.set_fact:
     cc: "{{ cc | ansible.builtin.combine(cc_secrets.cc,recursive=true)}}"
    when:
     - cc_secrets is defined
    
  - ansible.builtin.file:
      path: "{{item}}"
      state: touch 
    loop:
      - "/root/first_was_here_2"
    ignore_errors: true

  - ansible.builtin.template:
       src: "templates/{{ item }}.j2"
       dest: "{{ cc.cloud_init_shell }}"
    loop:
     - "cloud-init.sh"
    when:
     - ansible_user_id == "root"
  - user:
     name: ubuntu
     state: absent
     remove: yes


  - set_fact:
     myhostname: "{{ cc.rename[ansible_product_serial] }}"
    when:
     - cc.rename is defined
     - ansible_product_serial in cc.rename.keys()
     - myhostname is not defined

  - set_fact:
     myhostname: "{{ cc.rename[myserialhash] }}"
    when:
     - cc.rename is defined
     - myserialhash in cc.rename.keys()
     - myhostname is not defined


  - set_fact:
     myhostname: "{{ myhostname | default('ccl-%03d' | format(range(0,999) | random(seed=ansible_product_serial)))  }}"
    when:
     - myhostname is not defined


  - cron:
     name: "daily - config"
     job: test -f {{ cc.cloud_init_shell }} && flock -x  /tmp/robot /bin/bash  {{ cc.cloud_init_shell }}
     hour: 10
     minute: "{{ range(0,60) | random(seed=ansible_product_serial) }}"

  - name: "Set a hostname to {{myhostname}}"
    ansible.builtin.hostname:
     name: "{{ myhostname }}"
    notify:
        - reboot
  - ansible.builtin.user:
     name: "{{cc.username}}"
     comment: "{{cc.username}}@{{myhostname}}"
    notify:
        - reboot



  handlers:
    - name: reboot
      ansible.builtin.command:
        cmd: /usr/sbin/reboot
