- name: First run 
  hosts: localhost
  tasks:
  - ansible.builtin.file:
      path: "{{item}}"
      state: touch 
    loop:
      - "/root/first_was_here_2"
      - "/target/root/first_was_here_target_1"
    ignore_errors: true

