- name: First run 
  hosts: localhost
  vars_files:
   - vars/default.yaml 
  tasks:
  - ansible.builtin.file:
      path: "{{item}}"
      state: touch 
    loop:
      - "/root/first_was_here_2"
    ignore_errors: true
  - git:
     repo: "{{ cc.git }}"
     dest: "/root/laptop"
  - user:
     name: ubuntu
     state: absent
     remove: yes
