- name: Write hostname
  hosts: localhost
  vars_files:
   - vars/default.yaml 
  tasks:
  - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
    ansible.builtin.include_vars:
     name: cc_override
     files_matching: "{{alt | default('default.yaml')}}"
     dir: vars 
  - ansible.builtin.set_fact:
     cc_secrets: "{{ lookup('ansible.builtin.file', cc.secrets) | from_yaml  }}"
  
  - ansible.builtin.set_fact:
     cc: "{{ cc | ansible.builtin.combine(cc_secrets.cc,recursive=true) | ansible.builtin.combine(cc_override.cc,recursive=true) }}"
 
  - ansible.builtin.set_fact:
     cc_hash: "{{ lookup('ansible.builtin.pipe', 'mkpasswd -m yescrypt -s  '+cc.unixadmin) }}"  
     cc_hashu: "{{ lookup('ansible.builtin.pipe', 'mkpasswd -m yescrypt -s  '+cc.unixuser) }}"  
  - ansible.builtin.set_fact:
     cc: "{{ cc | ansible.builtin.combine({'hash':cc_hash,'hashu':cc_hashu}) }}"
  
  - ansible.builtin.set_fact:
     write_files: "{{ write_files|default([]) + [{'encoding' : 'b64' , 'path' : item.path , 'content': lookup('ansible.builtin.file', item.src) | b64encode }] }}"
    loop:
      - { path: '/root/boot.sh' , src: "boot.sh" }
      - { path: '/root/signatures' , src: "signatures" }
      - { path: '/etc/rc.local' , src: "once.sh" }
  - debug:
     msg: "{{ write_files }}"


  - ansible.builtin.set_fact:
     cc: "{{ cc | ansible.builtin.combine({'write_files': write_files}) }}"
    when:
     - write_files is defined

  - ansible.builtin.file:
       path: "{{ cc.cidatadir }}"
       state: directory
       mode: '0755'

  - ansible.builtin.template:
       src: "templates/{{ item }}.j2"
       dest: "{{ cc.cidatadir }}/{{ item }}"
    loop:
     - "user-data"
     - "meta-data"
     - "network-config"
     - "nocloud-usb.sh"
     - "media-usb.sh"







  - ansible.builtin.file:
       path: "{{ cc.cidatadir }}/{{ item }}"
       mode: '0755'
    loop:
     - "nocloud-usb.sh"
     - "media-usb.sh"
  - ansible.builtin.copy:
      src: files/signatures
      dest: "{{ cc.cidatadir }}/signatures"
  - debug:
      msg:
       - "Check file : cat {{ cc.cidatadir }}/user-data" 
       - "Insert a small usb and run {{ cc.cidatadir }}/nocloud-usb.sh"
       - "Insert a larger usb and run {{ cc.cidatadir }}/media-usb.sh"

  - name: "Burning nocloud stuff to {{ cc.dev }}"
    ansible.builtin.script: 
     cmd: "{{ cc.cidatadir }}/nocloud-usb.sh -f"
    args:
      executable: "/bin/bash" 

    
